workflows:
  ios-release:
    name: "iOS Release Build"
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace" # Update with your actual workspace name
        XCODE_SCHEME: "Runner" # Update with your actual scheme name
        # Add other environment variables if necessary
      xcode: "12.4.0" # Specify the Xcode version
      cocoapods: "default" # Use the default cocoapods version
      instance_type: mac_mini_m2 # Specify the instance type

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true

    scripts:
      - name: "Install dependencies"
        script: |
          flutter pub get
      - name: "Run tests"
        script: |
          flutter test
      - name: "Build iOS release"
        script: |
          flutter build ios --release --no-codesign
      - name: "Post-processing"
        script: |
          # Additional scripts like code signing or other post-build steps can be added here

    artifacts:
      - build/ios/ipa/*.ipa # This will collect the .ipa file from the specified path

    publishing:
      email:
        recipients:
          - email@example.com # Specify your email here
        notify_on_build_start: true
        notify_on_build_success: true
        notify_on_build_failure: true
